### ISSUE TITLE
Items View cannot be used due to outdated CommunityToolkit nuget packages

### ISSUE THREAD

**Issue by D-Naveenz** [CommunityToolkit/Windows#402] opened 2024-04-18 05:48 UTC
### Describe the bug

UI controls that inherit Items Repeater, such as Items View, cannot be used in a project. It produces an error,
`Failed to assign to property 'Microsoft.UI.Xaml.Controls.ItemsRepeater.ItemTransitionProvider'`

My project is using the latest packages.

- WinAppSDK 1.5
- Dot Net 8.0

There is a detailed discussion ongoing here: https://github.com/microsoft/microsoft-ui-xaml/issues/8810
According to the information,
"Calling out here that `CommunityToolkit.WinUI.UI.Controls` is the old package from 7.x built against WASDK 1.0"

So, the main problem comes with the XamlMetaDataProviders loading order.
But that's not the only problem; `CommunityToolkit.WinUI.UI` packages are heavily outdated and isn't compatible with the Windows Community Toolkit Gallery App.
Ex: SettingsCard control is not there.

### Steps to reproduce

```text
1) Make a WinUI 3 Application using Template Studio (easier way)
2) Add an ItemsView control in a page
3) Try to run the application
```

### Expected behavior

1. Correctly generate code from XAML scripts.
2. Compatible with the Windows Community Toolkit Gallery App

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [X] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Device form factor

Desktop

### Additional context

There is a temporary solution.

In your app's csproj file add this property to the first PropertyGroup:
`<XamlCodeGenerationControlFlags>DoNotGenerateOtherProviders</XamlCodeGenerationControlFlags>`

This will cause the Xaml Compiler to not populate the OtherProviders list. You now need to populate it manually. In your App's constructor, call AddOtherProvider to add each of the IXamlMetadataProviders that were previously being generated. Since you can now control the order you can make sure that XamlControlsXamlMetaDataProvider comes first:

> var xmpList = new MetadataProviders().GetAll();
> foreach (var xmp in xmpList)
> {
>     _AddOtherProvider(xmp);
> }

> metadataProviders.Add(new Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_Core_XamlTypeInfo.XamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_DataGrid_XamlTypeInfo.XamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_Input_XamlTypeInfo.XamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_Layout_XamlTypeInfo.XamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_Markdown_XamlTypeInfo.XamlMetaDataProvider());
> metadataProviders.Add(new CommunityToolkit.WinUI.UI.Controls.CommunityToolkit_WinUI_UI_Controls_Media_XamlTypeInfo.XamlMetaDataProvider());

### Help us help you

Yes, but only if others can assist.

**Comment by michael-hawker** [comment] 2024-04-22 16:48
Duplicate of #234. The issue you linked to in the WinUI repo is tracking this issue with the SDK. We've been discussing this issue with them as every WASDK release which introduces a new component has been hitting this issue.

All the 7.x packages are old, for instance `CommunityToolkit.WinUI.UI.Controls.Primitives` is now just `CommunityToolkit.WinUI.Controls.Primitives`, see the [8.0 release blog with more info](https://devblogs.microsoft.com/ifdef-windows/announcing-windows-community-toolkit-v8-0/)

For now, the latest 8.1-rc build on NuGet resolves this issue by targeting the latest WASDK version, we hope to ship the full release soon.

**Closed by michael-hawker** 2024-04-22 16:48 UTC

**Comment by D-Naveenz** [comment] 2024-05-10 12:38
Is there a way to get the 8.1-rc NuGet package, or can I build it by cloning the project?
