### ISSUE TITLE
Segmented disappeared in last update

### ISSUE THREAD

**Issue by andresledo** [CommunityToolkit/Windows#544] opened 2024-08-26 10:01 UTC
### Describe the bug

When installing the latest version of the nugget package this control has disappeared. The Microsoft page shows a 404 error, this control has been removed?

https://learn.microsoft.com/es-es/windows/segmented

### Reproducible in sample app?

- [ ] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
Upgrade to the latest available nugget package
```

### Expected behavior

Component works in the latest version

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment] 2024-11-13 22:50
Closing as duplicate of https://github.com/CommunityToolkit/Windows/issues/494

**Closed by Arlodotexe** 2024-11-13 22:50 UTC
