### ISSUE TITLE
[SettingCard] Header and description disappered with Microsoft.WindowsAppSDK 1.6 Preview 1

### ISSUE THREAD

**Issue by Jimex** [CommunityToolkit/Windows#473] opened 2024-08-18 08:53 UTC
### Describe the bug

The header and description didn't appear in the WinUI 3 project using Microsoft.WindowsAppSDK 1.6 Preview 1

### Steps to reproduce

```text
- Use a new SettingCard Control in  Microsoft.WindowsAppSDK 1.6 Preview 1 (1.6.240807006-preview1) application.
- Run the application
```

### Expected behavior

The header and the description should display correctly

### Screenshots

**Expected (Before Microsoft.WindowsAppSDK 1.6 Preview 1)**
![image](https://github.com/user-attachments/assets/177e288d-a96c-45d1-a27c-a6dc4def42c5)

**Actual (With Microsoft.WindowsAppSDK 1.6 Preview 1) **
![image](https://github.com/user-attachments/assets/00624aff-97fb-4801-91c9-5a55b1a3f570)

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [X] Windows 10, version 1809 (Build 17763)
- [X] Windows 10, version 1903 (Build 18362)
- [X] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [X] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

CommunityToolkit.WinUI.Controls.SettingsControls 8.1.240606-rc

### Visual Studio Version

2022

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment] 2024-08-19 17:58
Thanks, we're tracking this issue with the platform and following-up with them in their issue here: https://github.com/microsoft/WindowsAppSDK/issues/4649

We believe this is a regression as we see the issue with the old package as well as ones built against preview1.

**Comment by RobertK66** [comment] 2024-08-23 06:01
Works in Preview 2 now. 👍

**Comment by michael-hawker** [comment] 2024-08-23 14:27
Thanks @RobertK66 for the report, was that with our older 8.0 builds or the newly released 8.1?

**Comment by RobertK66** [comment] 2024-08-24 06:20
It works with both the 8.0 and the 8.1 bits.
My Windows 11 is: 23H2 build: 22631.4037

**Comment by Arlodotexe** [comment] 2024-09-10 21:51
@Jimex Can you confirm whether the issue is solved in your project with the latest bits?

**Comment by Jimex** [comment] 2024-09-10 22:17
> @Jimex Can you confirm whether the issue is solved in your project with the latest bits?

Yeah, I checked, and it looks like the issue is solved with 1.6!

**Comment by michael-hawker** [comment] 2024-09-11 02:27
Closing this as this was an issue specifically with Windows App SDK 1.6-preview1 which has been resolved now.

**Closed by michael-hawker** 2024-09-11 02:27 UTC
