### ISSUE TITLE
The sliders of RangeSelector and ColorPicker do not support touch screens, and ColorPickerButton does not support setting IsAlphaEnabled and AlphaSliderVisible.

### ISSUE THREAD

**Issue by SQc04** [CommunityToolkit/Windows#520] opened 2024-09-22 17:17 UTC
### Describe the bug

The sliders of RangeSelector and ColorPicker do not support touch screens, and ColorPickerButton does not support setting IsAlphaEnabled and AlphaSliderVisible.

### Steps to reproduce

```text
Drag the sliders of RangeSelector and ColorPicker using a touch screen.
```

### Expected behavior

The sliders should be draggable rather than only allowing position setting through clicking.

### Screenshots

![image](https://github.com/user-attachments/assets/b7fb964c-22a6-49e5-b299-de874a34472b)
![image](https://github.com/user-attachments/assets/10f50686-f264-454c-b671-efd846f63ae0)
![image](https://github.com/user-attachments/assets/91d5ea79-e150-42be-8893-6289b624b687)
![image](https://github.com/user-attachments/assets/684b28c7-b0fc-484d-9b47-a6ab9b741438)
![image](https://github.com/user-attachments/assets/5864b656-650f-48e7-92d6-cc868e6cdafa)

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Device form factor

Desktop

### Help us help you

No, I'm unable to contribute a solution.

**Comment by Arlodotexe** [comment] 2024-09-25 17:26
Duplicate of #486

**Closed by Arlodotexe** 2024-09-25 17:26 UTC
