### ISSUE TITLE
GridSplitter invisible when added in C# (just 'Control' in Live Visual Tree), but visible when added in xaml

### ISSUE THREAD

**Issue by TRadigk** [CommunityToolkit/Windows#502] opened 2024-09-09 06:30 UTC
### Describe the bug

Adding a GridSplitter in C# will not let it render. Adding it in XAML though will let it render.
Also: When added in XAML it is a resolved component in the Live Visual Tree, while when added in C# it is just "Control":

Added in XAML:
![grafik](https://github.com/user-attachments/assets/c303b9d3-cae4-4e53-9c8b-33125957886f)

MainWindow XAML:
```
<Window
    x:Class="CommunityToolkitTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:CommunityToolkitTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:CommunityToolkit.WinUI.Controls"
    mc:Ignorable="d">

    <Grid ColumnSpacing="10">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>

        <Border BorderThickness="1" Grid.Row="0" BorderBrush="Green" Grid.Column="0" />
        <Border BorderThickness="1" Grid.Row="0" BorderBrush="Red" Grid.Column="1" />


        <controls:GridSplitter Grid.Row="0" Grid.Column="1" HorizontalAlignment="Left"
                               ResizeBehavior="BasedOnAlignment"
                               ResizeDirection="Auto">
        </controls:GridSplitter>
    </Grid>
</Window>
```
MainWindow C#:
```
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }
}
```

Added in C#:
![grafik](https://github.com/user-attachments/assets/a380781b-265e-4155-9f17-9b839360db64)

MainWindow XAML:
```
<Window
    x:Class="CommunityToolkitTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:CommunityToolkitTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:CommunityToolkit.WinUI.Controls"
    mc:Ignorable="d">

</Window>
```
MainWindow C#:
```
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();

        var grid = new Grid
        {
            ColumnSpacing = 10
        };
        grid.ColumnDefinitions.Add(new ColumnDefinition());
        grid.ColumnDefinitions.Add(new ColumnDefinition());

        var gridSplitter = new GridSplitter
        {
            ResizeBehavior = GridSplitter.GridResizeBehavior.BasedOnAlignment,
            ResizeDirection = GridSplitter.GridResizeDirection.Auto,
            HorizontalAlignment = HorizontalAlignment.Left,
        };

        var borderLeft = new Border
        {
            BorderThickness = new Thickness(1),
            BorderBrush = new SolidColorBrush(Colors.Green)
        };
        var borderRight = new Border
        {
            BorderThickness = new Thickness(1),
            BorderBrush = new SolidColorBrush(Colors.Red)
        };
        grid.Children.Add(borderRight);
        grid.Children.Add(borderLeft);
        Grid.SetColumn(borderRight, 1);
        Grid.SetColumn(borderLeft, 0);
        Grid.SetColumn(gridSplitter, 1);
        grid.Children.Add(gridSplitter);
        Content = grid;
    }
}
```

### Steps to reproduce

```text
1. Create new Winui Desktop App unpackaged.
2. Ensure Windows App SDK package version is 1.6.240829007
3. Ensure <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
4. Add nuget package CommunityToolkit.WinUI.Controls.Sizers 8.1.240821
5. Use code from issue to reproduce
```

### Expected behavior

The GridSplitter is visible when added in C#, like it is visible when added in XAML.

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

Windows 11 24H2 26100.1591

### App minimum and target SDK version

- [X] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022, Preview

### Visual Studio Build Number

Version 17.12.0 Preview 1.0

### Device form factor

Desktop

### Help us help you

No, I'm unable to contribute a solution.

**Comment by TRadigk** [comment] 2024-09-09 06:35
Additional investigations: Other controls like a radial Gauge can be added without any problems. But the grid splitter can't even be added  with 8.0.230907 or 8.0.240109:
![grafik](https://github.com/user-attachments/assets/cabde167-761c-4f67-a48c-909f1bca87c2)

**Comment by michael-hawker** [comment] 2024-09-10 21:03
Duplicate of #273

**Closed by michael-hawker** 2024-09-10 21:03 UTC
